### PR TITLE
WIP: Implementation in Nonconvex.jl

### PR DESCRIPTION
**Pull request by ccoffrin**
Currently testing with, 
```
  [b6b21f68] Ipopt v1.0.2
  [01bcebdf] Nonconvex v1.0.4
  [bf347577] NonconvexIpopt v0.1.4
  [c48e48a2] NonconvexUtils v0.2.1 `https://github.com/JuliaNonconvex/NonconvexUtils.jl.git#main`
  [c36e90e8] PowerModels v0.19.5
```

I have attempted to implement the full model.  So far no crashes but Ipopt does not converge, there seems to be an issue with how the `inequality constraint Jacobian` is treated, so I can not yet verify there is not a bug in my model's implementation. Adding any one of the nonlinear equality constraints seems sufficient to present the issue. It appears for the moment that the Jacobian/Hessian are not sparse so I use the `NLPModels`  Ipopt trace as a point of reference.

**NLPModels (expected Ipopt log)**
```
include("nlpmodels.jl"); solve_opf("data/pglib_opf_case5_pjm.m")
...
variables: 44, 44, 44
constraints: 53, 53, 53
...
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:     1540
Number of nonzeros in inequality constraint Jacobian.:      792
Number of nonzeros in Lagrangian Hessian.............:      990

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       18
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        6
        inequality constraints with only upper bounds:       12

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 3.99e+00 2.88e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  8.3066346e+03 2.47e+00 1.01e+02  -1.0 2.78e+00    -  4.11e-03 3.82e-01h  1
   2  6.7182484e+03 2.36e+00 9.62e+01  -1.0 1.60e+01    -  7.37e-02 4.44e-02f  1
...
```

**Nonconvex (Ipopt log)**
```
include("nonconvex.jl"); solve_opf("data/pglib_opf_case5_pjm.m")
...
variables: 44
constraints: 59
...
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:     1540
Number of nonzeros in inequality constraint Jacobian.:     1056
Number of nonzeros in Lagrangian Hessian.............:      990

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       24
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       24

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 1.74e+01 1.48e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  4.5147526e+02 1.74e+01 7.76e+03  -1.0 5.87e+01    -  1.69e-04 1.68e-02h  1
   2  4.6093397e+02 1.74e+01 8.07e+03  -1.0 4.07e+01   2.0 4.54e-03 2.71e-04h  1
...
```
The trace for Nonconvex fails to converge and iterates indefinitely (it should converge in 21 iterations).  Looking at the Ipopt information, the number of _constraints_ and _number of inequality constraints_ is expected to change as Nonconvex only supports one sided inequalities, from what I could tell. This increases the number of constraints by 6. These two sided constaints can also be removed for debugging and the model still does not converge.

The difference in the _Number of nonzeros in inequality constraint Jacobian_ seems to be the most likely source of the issue to me.

@odow @mohamed82008 any ideas?

### CODE REVIEW

**Comment by odow** [comment]
I'll take a look.

**Comment by odow** [comment]
I came back to take a look at this, but looks like @mohamed82008 has been working hard;
 * https://github.com/JuliaNonconvex/NonconvexUtils.jl/pull/11
 * https://github.com/JuliaNonconvex/NonconvexIpopt.jl/pull/8
 * https://github.com/JuliaNonconvex/NonconvexCore.jl/commit/d67bbee487b82050d72b23b7c59e9523d093d012

I'm just chasing own the changes that were made. Seems like `Nonconvex.symbolify` doesn't exist any more.

**Comment by odow** [comment]
Ah. I just needed `import NonconvexUtils`.

With
```
  [01bcebdf] Nonconvex v1.0.3
  [bf347577] NonconvexIpopt v0.2.0
  [c48e48a2] NonconvexUtils v0.3.0
```
things are still dense and not converging
```
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:     1540
Number of nonzeros in inequality constraint Jacobian.:     1056
Number of nonzeros in Lagrangian Hessian.............:      990

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       24
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       24

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 1.74e+01 1.48e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  4.5147526e+02 1.74e+01 7.76e+03  -1.0 5.87e+01    -  1.69e-04 1.68e-02h  1
   2  4.6093397e+02 1.74e+01 8.07e+03  -1.0 4.07e+01   2.0 4.54e-03 2.71e-04h  1
   3r 4.6093397e+02 1.74e+01 9.99e+02   1.3 0.00e+00   1.5 0.00e+00 1.63e-10R 24
   4r 4.7173318e+02 1.74e+01 9.99e+02   1.3 1.56e+04    -  2.12e-04 7.10e-05f  1
   5r 5.2733753e+02 2.56e+01 9.99e+02   1.3 1.29e+04    -  1.25e-04 5.86e-04f  1
   6r 6.3546788e+02 6.94e+01 9.98e+02   1.3 8.43e+03    -  9.25e-04 7.50e-04f  1
   7r 9.5670264e+02 1.18e+02 9.97e+02   1.3 3.68e+03    -  4.20e-04 1.42e-03f  1
   8r 1.3324925e+03 8.35e+01 9.96e+02   1.3 7.31e+03    -  1.23e-03 1.72e-03f  1
```

Are you still working on some changes @mohamed82008?

**Comment by mohamed82008** [comment]
>Are you still working on some changes @mohamed82008?

Yes. I just released some updated in `NonconvexIpopt` and `NonconvexUtils` that enforce sparsity. You just need to pass the `sparse = true` option to `IpoptOptions`.

**Comment by mohamed82008** [comment]
There was also a bug in the Hessian computation that I fixed so try again. Still fixing errors in Hessians of vector-valued functions and running more tests so things aren't fully stable yet but they are getting there.

**Comment by odow** [comment]
Partial progress. I now get a sparse Jacobian, but it errors on evaluation:
```Julia
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:      155
Number of nonzeros in inequality constraint Jacobian.:       48
Number of nonzeros in Lagrangian Hessian.............:       37

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       24
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       24

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 1.74e+01 1.48e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
ERROR: BoundsError: attempt to access 37-element Vector{Float64} at index [35:40]
Stacktrace:
  [1] throw_boundserror(A::Vector{Float64}, I::Tuple{UnitRange{Int64}})
    @ Base ./abstractarray.jl:691
  [2] checkbounds
    @ ./abstractarray.jl:656 [inlined]
  [3] view
    @ ./subarray.jl:177 [inlined]
  [4] maybeview
    @ ./views.jl:146 [inlined]
  [5] dotview
    @ ./broadcast.jl:1200 [inlined]
  [6] add_values!(values::Vector{Float64}, HL::LowerTriangular{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}; factor::Int64, offset::Int64)
    @ NonconvexCore ~/.julia/packages/NonconvexCore/nK7uX/src/models/moi.jl:299
  [7] add_values!(values::Vector{Float64}, HL::LowerTriangular{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}})
    @ NonconvexCore ~/.julia/packages/NonconvexCore/nK7uX/src/models/moi.jl:295
  [8] (::NonconvexIpopt.var"#8#16"{Bool, NonconvexIpopt.var"#lag#10"{NonconvexCore.CountingFunction{NonconvexCore.Objective{NonconvexCore.var"#144#151"{DictModel, NonconvexCore.Unflatten{OrderedDict{String, Float64}, NonconvexCore.var"#unflatten_to_Dict#75"{typeof(identity), OrderedDict{String, Float64}}}}, Base.RefValue{Float64}, Set{Symbol}}}, NonconvexCore.VectorOfFunctions{Vector{NonconvexCore.IneqConstraint{var"299", Float64, Int64, Set{Symbol}} where var"299"<:Function}}, NonconvexCore.VectorOfFunctions{Vector{NonconvexCore.EqConstraint{var"303", Float64, Int64, Set{Symbol}} where var"303"<:Function}}}})(x::Vector{Float64}, rows::Vector{Int32}, cols::Vector{Int32}, obj_factor::Float64, lambda::Vector{Float64}, values::Vector{Float64})
    @ NonconvexIpopt ~/.julia/packages/NonconvexIpopt/zl6RS/src/ipopt.jl:211
  [9] _Eval_H_CB(n::Int32, x_ptr::Ptr{Float64}, #unused#::Int32, obj_factor::Float64, m::Int32, lambda_ptr::Ptr{Float64}, #unused#::Int32, nele_hess::Int32, iRow::Ptr{Int32}, jCol::Ptr{Int32}, values_ptr::Ptr{Float64}, user_data::Ptr{Nothing})
    @ Ipopt ~/.julia/packages/Ipopt/M2QE8/src/C_wrapper.jl:122
 [10] IpoptSolve(prob::Ipopt.IpoptProblem)
    @ Ipopt ~/.julia/packages/Ipopt/M2QE8/src/C_wrapper.jl:433
 [11] optimize!(workspace::NonconvexIpopt.IpoptWorkspace{NonconvexCore.VecModel{NonconvexCore.Objective{NonconvexCore.var"#144#151"{DictModel, NonconvexCore.Unflatten{OrderedDict{String, Float64}, NonconvexCore.var"#unflatten_to_Dict#75"{typeof(identity), OrderedDict{String, Float64}}}}, Base.RefValue{Float64}, Set{Symbol}}, NonconvexCore.VectorOfFunctions{Vector{NonconvexCore.EqConstraint{var"303", Float64, Int64, Set{Symbol}} where var"303"<:Function}}, NonconvexCore.VectorOfFunctions{Vector{NonconvexCore.IneqConstraint{var"299", Float64, Int64, Set{Symbol}} where var"299"<:Function}}, NonconvexCore.VectorOfFunctions{Vector{NonconvexCore.SDConstraint}}, Vector{Float64}, Vector{Float64}, Vector{Float64}}, Ipopt.IpoptProblem, Vector{Float64}, IpoptOptions{NamedTuple{(:hessian_approximation, :jac_c_constant, :jac_d_constant, :sparse), Tuple{String, String, String, Bool}}}, Base.RefValue{Int64}})
    @ NonconvexIpopt ~/.julia/packages/NonconvexIpopt/zl6RS/src/ipopt.jl:56
 [12] #optimize#142
    @ ~/.julia/packages/NonconvexCore/nK7uX/src/models/vec_model.jl:63 [inlined]
 [13] optimize(::DictModel, ::IpoptAlg, ::OrderedDict{String, Float64}; kwargs::Base.Pairs{Symbol, IpoptOptions{NamedTuple{(:hessian_approximation, :jac_c_constant, :jac_d_constant, :sparse), Tuple{String, String, String, Bool}}}, Tuple{Symbol}, NamedTuple{(:options,), Tuple{IpoptOptions{NamedTuple{(:hessian_approximation, :jac_c_constant, :jac_d_constant, :sparse), Tuple{String, String, String, Bool}}}}}})
    @ NonconvexCore ~/.julia/packages/NonconvexCore/nK7uX/src/common.jl:233
 [14] solve_opf(file_name::String)
    @ Main ~/Documents/lanl-ansi/rosetta-opf/nonconvex.jl:232
 [15] top-level scope
    @ REPL[11]:1
```

**Comment by mohamed82008** [comment]
that's definitely a bug, please open an issue with a MWE

**Comment by odow** [comment]
Here you go: https://github.com/JuliaNonconvex/Nonconvex.jl/issues/140

The model problem is quite nice for testing. It's small, but quite tricky for AD to get right.

**Comment by mohamed82008** [comment]
Thanks, once I fix the known bugs I am working on, I will look into it. I will be on a long flight tomorrow with nothing better to do, so 🤞

**Comment by ccoffrin** [comment]
@mohamed82008 I was wondering if you had a tentative ETA on these bug fixes?  This is the last blocking issue for me to re-run the experiments.

**Comment by mohamed82008** [comment]
See the explanation in https://github.com/JuliaNonconvex/Nonconvex.jl/issues/140. You can use NonconvexIpopt 0.4 and Nonconvex 2.0 (https://github.com/JuliaRegistries/General/pull/62556) to test your examples. If you don't run into the issue I describe, your examples should work.

**Comment by mohamed82008** [comment]
I also updated the docs so they have all the new cool features documented https://julianonconvex.github.io/Nonconvex.jl/dev/, especially in the "Gradients, Jacobians and Hessians" section.

**Comment by ccoffrin** [comment]
This appears to be working with `Nonconvex v2.0.1` and `NonconvexIpopt v0.3.0`.  Thanks a lot of the bug fixes @mohamed82008!

Here is the working log on the 5 bus case, 
```
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:      155
Number of nonzeros in inequality constraint Jacobian.:       48
Number of nonzeros in Lagrangian Hessian.............:       56

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       24
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       24

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 1.74e+01 1.48e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.4916293e+02 1.73e+01 7.09e+01  -1.0 5.67e+01    -  1.75e-04 1.77e-03h  1
   2  1.4804743e+04 5.48e+00 1.61e+03  -1.0 7.26e+01    -  1.46e-03 5.58e-01h  1
   3  1.4900905e+04 5.46e+00 1.59e+03  -1.0 1.35e+01   2.0 1.84e-02 3.22e-03h  1
   4  1.8125340e+04 4.57e+00 1.10e+03  -1.0 1.35e+01   2.4 5.37e-02 1.64e-01h  1
   5  1.8229110e+04 4.53e+00 1.13e+03  -1.0 1.57e+01   1.9 4.51e-01 8.36e-03h  1
   6  2.0353996e+04 2.99e+00 1.56e+03  -1.0 1.72e+01    -  1.74e-01 3.40e-01h  1
   7  2.2048219e+04 1.69e+00 1.40e+03  -1.0 1.34e+01    -  1.27e-01 4.35e-01h  1
   8  2.3830758e+04 9.18e-02 9.48e+02  -1.0 1.09e+01    -  1.24e-01 1.00e+00h  1
   9  2.2321066e+04 1.49e-01 1.02e+03  -1.0 1.75e+01    -  5.36e-02 1.09e-01f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  2.2248475e+04 1.48e-01 1.02e+03  -1.0 1.62e+01    -  2.79e-02 5.08e-03f  1
  11  1.7683756e+04 9.19e-01 1.01e+03  -1.0 3.73e+01    -  7.01e-03 9.86e-02f  1
  12  1.7636592e+04 9.17e-01 1.00e+03  -1.0 5.93e+00    -  2.54e-01 1.02e-02f  1
  13  1.7653500e+04 4.46e-01 2.65e+02  -1.0 2.28e+00    -  5.24e-01 7.29e-01h  1
  14  1.7625631e+04 1.19e-01 6.75e+01  -1.0 1.24e+00    -  1.75e-01 7.17e-01f  1
  15  1.7606450e+04 1.47e-02 3.75e+01  -1.0 1.09e+00    -  8.94e-01 1.00e+00f  1
  16  1.7582486e+04 7.69e-03 3.59e+01  -1.0 1.10e+00    -  1.00e+00 8.71e-01h  1
  17  1.7588259e+04 1.38e-03 2.07e+01  -1.0 3.60e-01    -  1.00e+00 1.00e+00f  1
  18  1.7586866e+04 6.41e-04 1.70e+01  -1.0 1.94e-01    -  1.00e+00 1.00e+00h  1
  19  1.7589215e+04 3.51e-05 6.44e+00  -1.0 3.40e-02    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  20  1.7590578e+04 5.81e-08 8.46e-02  -1.0 6.03e-03    -  1.00e+00 1.00e+00h  1
  21  1.7558794e+04 3.37e-03 5.16e+01  -2.5 5.23e-01    -  8.82e-01 9.26e-01f  1
  22  1.7552552e+04 4.12e-03 6.34e+01  -2.5 1.22e-01    -  1.00e+00 9.91e-01h  1
  23  1.7553015e+04 2.83e-05 5.19e+00  -2.5 7.43e-03    -  1.00e+00 1.00e+00h  1
  24  1.7552886e+04 5.22e-06 2.67e+00  -2.5 1.24e-03    -  1.00e+00 1.00e+00h  1
  25  1.7552877e+04 2.65e-08 1.90e-01  -2.5 2.96e-04    -  1.00e+00 1.00e+00h  1
  26  1.7552877e+04 2.03e-12 6.68e-04  -2.5 1.72e-05    -  1.00e+00 1.00e+00h  1
  27  1.7551986e+04 4.80e-06 1.93e+00  -3.8 2.40e-02    -  1.00e+00 9.23e-01f  1
  28  1.7551937e+04 1.16e-07 8.49e-02  -3.8 7.36e-03    -  1.00e+00 1.00e+00f  1
  29  1.7551940e+04 2.99e-10 7.38e-03  -3.8 4.68e-04    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  30  1.7551940e+04 1.61e-13 1.58e-04  -3.8 1.01e-05    -  1.00e+00 1.00e+00h  1
  31  1.7551893e+04 1.74e-07 2.08e-01  -5.7 2.49e-03    -  1.00e+00 9.68e-01f  1
  32  1.7551891e+04 7.25e-11 3.31e-03  -5.7 2.44e-04    -  1.00e+00 1.00e+00f  1
  33  1.7551891e+04 2.24e-14 3.34e-06  -5.7 1.89e-07    -  1.00e+00 1.00e+00h  1
  34  1.7551891e+04 6.09e-12 9.94e-04  -8.6 3.51e-05    -  1.00e+00 1.00e+00f  1
  35  1.7551891e+04 2.86e-14 1.34e-06  -8.6 8.37e-08    -  1.00e+00 1.00e+00h  1
  36  1.7551891e+04 3.35e-14 7.46e-09  -8.6 4.65e-10    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 36

                                   (scaled)                 (unscaled)
Objective...............:   4.3879727248486819e+02    1.7551890899394726e+04
Dual infeasibility......:   7.4560270639326334e-09    2.9824108255730534e-07
Constraint violation....:   2.1672974526154574e-14    3.3528735343679728e-14
Variable bound violation:   2.9463905093507492e-08    2.9463905093507492e-08
Complementarity.........:   2.5059035792274208e-09    1.0023614316909683e-07
Overall NLP error.......:   7.4560270639326334e-09    2.9824108255730534e-07


Number of objective function evaluations             = 37
Number of objective gradient evaluations             = 37
Number of equality constraint evaluations            = 37
Number of inequality constraint evaluations          = 37
Number of equality constraint Jacobian evaluations   = 37
Number of inequality constraint Jacobian evaluations = 37
Number of Lagrangian Hessian evaluations             = 36
Total seconds in IPOPT                               = 9.191

EXIT: Optimal Solution Found.
```

It takes a few more iterations than the JuMP version (below), but they converge to the same solution value up to 8 digits, indicating correctness of the formulation. I suspect this difference in iterations is due to an error in the Hessian, (JuMP Symbolic AD finds 63 non-zeros where Nonconvex finds only 56). In either case I can proceed with this version of the code as the models appears to be correct and it is converging.
```
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:      155
Number of nonzeros in inequality constraint Jacobian.:       48
Number of nonzeros in Lagrangian Hessian.............:       63

Total number of variables............................:       44
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       39
                     variables with only upper bounds:        0
Total number of equality constraints.................:       35
Total number of inequality constraints...............:       24
        inequality constraints with only lower bounds:        6
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       18

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0059989e+02 3.99e+00 2.88e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  8.3066305e+03 2.47e+00 1.01e+02  -1.0 2.78e+00    -  4.11e-03 3.82e-01h  1
   2  6.7181372e+03 2.36e+00 9.62e+01  -1.0 1.60e+01    -  7.37e-02 4.44e-02f  1
   3  6.6689587e+03 2.30e+00 9.34e+01  -1.0 1.30e+01    -  4.94e-01 2.40e-02f  1
   4  6.5741805e+03 2.04e+00 8.25e+01  -1.0 1.29e+01    -  3.67e-01 1.12e-01f  2
   5  6.8264259e+03 1.80e+00 7.10e+01  -1.0 1.23e+01    -  8.72e-01 1.20e-01h  2
   6  8.8540136e+03 1.08e+00 4.20e+01  -1.0 9.14e+00    -  5.92e-01 4.00e-01h  1
   7  1.0572806e+04 8.62e-01 3.58e+01  -1.0 2.94e+00    -  4.93e-01 2.00e-01h  1
   8  1.7308578e+04 3.63e-02 1.46e+01  -1.0 2.41e+00    -  7.65e-01 9.58e-01h  1
   9  1.7572868e+04 1.33e-02 1.10e+00  -1.0 2.11e+00    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  1.7590631e+04 1.68e-03 1.61e-01  -1.0 5.04e-01    -  1.00e+00 1.00e+00h  1
  11  1.7558724e+04 5.24e-03 5.03e-01  -2.5 6.03e-01    -  8.35e-01 9.36e-01f  1
  12  1.7553111e+04 3.34e-03 4.12e+00  -2.5 2.84e-01    -  1.00e+00 8.20e-01h  1
  13  1.7552956e+04 3.24e-05 1.26e-02  -2.5 6.35e-02    -  1.00e+00 1.00e+00h  1
  14  1.7551990e+04 1.35e-05 1.09e+00  -3.8 2.53e-02    -  1.00e+00 9.25e-01h  1
  15  1.7551938e+04 4.46e-08 1.22e-02  -3.8 7.00e-03    -  1.00e+00 1.00e+00f  1
  16  1.7551940e+04 2.35e-10 2.06e-04  -3.8 3.84e-04    -  1.00e+00 1.00e+00h  1
  17  1.7551892e+04 1.75e-07 2.11e-01  -5.7 2.49e-03    -  1.00e+00 9.68e-01f  1
  18  1.7551891e+04 6.82e-11 3.10e-05  -5.7 2.38e-04    -  1.00e+00 1.00e+00f  1
  19  1.7551891e+04 3.73e-14 6.53e-10  -5.7 5.20e-07    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  20  1.7551891e+04 6.34e-12 3.03e-07  -8.6 3.52e-05    -  1.00e+00 1.00e+00f  1
  21  1.7551891e+04 1.98e-14 1.77e-12  -8.6 3.34e-08    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 21

                                   (scaled)                 (unscaled)
Objective...............:   4.3879727096486880e+02    1.7551890838594751e+04
Dual infeasibility......:   1.7716992512160599e-12    7.0867970048642396e-11
Constraint violation....:   1.4432899320127035e-14    1.9761969838327786e-14
Variable bound violation:   2.9463905093507492e-08    2.9463905093507492e-08
Complementarity.........:   2.5059076302146216e-09    1.0023630520858486e-07
Overall NLP error.......:   2.5059076302146216e-09    1.0023630520858486e-07


Number of objective function evaluations             = 28
Number of objective gradient evaluations             = 22
Number of equality constraint evaluations            = 28
Number of inequality constraint evaluations          = 28
Number of equality constraint Jacobian evaluations   = 22
Number of inequality constraint Jacobian evaluations = 22
Number of Lagrangian Hessian evaluations             = 21
Total seconds in IPOPT                               = 0.835

EXIT: Optimal Solution Found.
```

**Comment by odow** [comment]
See https://github.com/JuliaNonconvex/Nonconvex.jl/issues/140#issuecomment-1159214582. It's possible we will still hit bugs if there are structural zeros in the initial hessian.

**Comment by mohamed82008** [comment]
This is a good example I can use as a test case. Would be nice to identify the source of the discrepancy.

**Comment by mohamed82008** [comment]
Nonconvex is at fault here. I will go with the third solution suggested in my comment above. This should fix all the issues and simplify the API.

**Pull request merged**
