### PR TITLE
Refactor into a common utils.jl for parsing and loading the data

### PR DESCRIPTION
**Pull request by odow**
I was taking a look at the implementations and got bogged down by the large amount of duplicated code between the implementations. It made it hard to see what was what.

Hopefully this will help avoid mistakes between implementations, and clarifies what is unique to each modeling layer.

Currently jump.jl and nonconvex.jl are excluded from this refactor because their modeling API is incremental instead of accepting everything at once.

### CODE REVIEW

**Comment by ccoffrin** [comment]
I considered doing this but in the end I thought it would be better if each script was independent from each other.  Who knows, maybe it is possible to have implementations that are tailored to each of these modeling layers that are based around Julia function APIs.  Time will tell.  At least for now I suggest that we hold off merging this until some time has passed for the package developers to propose changes to their implementations.  If the basics remain the same, then I am open to revisiting this.

**Comment by odow** [comment]
Ah okay. At least Optim still has the convergence issue if we use the `utils.jl`, so that rules out a typo somewhere in the constraints.

**Comment by ccoffrin** [comment]
Good to know! I checked Optim quite thoroughly, I am pretty sure the modeling side is correct.

Maybe one middle ground we can do in the near term is to have the files that are very similar to have identical line numbers for the repeated code blocks (this is almost the case already).  Then `diff` at the command line can be used to quickly see what is different between them?

**Comment by odow** [comment]
Closing for now.

**Pull request closed without merging**
